const words = [
  "apple",
  "banana",
  "orange",
  "grape",
  "strawberry",
  "watermelon",
  "pineapple",
  "kiwi",
  "peach",
  "pear",
  "blueberry",
  "raspberry",
  "mango",
  "cherry",
  "lemon",
  "lime",
  "coconut",
  "apricot",
  "plum",
  "fig",
  "avocado",
  "pomegranate",
  "blackberry",
  "cranberry",
  "elderberry",
  "tangerine",
  "grapefruit",
  "melon",
  "nectarine",
  "papaya",
  "lychee",
  "dragonfruit",
  "guava",
  "passionfruit",
  "starfruit",
  "persimmon",
  "kumquat",
  "plantain",
  "boysenberry",
  "cantaloupe",
  "durian",
  "rhubarb",
  "jackfruit",
  "breadfruit",
  "mulberry",
  "quince",
  "soursop",
  "tamarind",
  "ugli fruit",
  "ackee",
  "cherimoya",
  "date",
  "feijoa",
  "longan",
  "loquat",
  "mangosteen",
  "rambutan",
  "sapote",
  "sugar apple",
  "carambola",
  "custard apple",
  "kiwano",
  "soursop",
  "salak",
  "rowanberry",
  "lingonberry",
  "cloud berry",
  "bearberry",
  "gooseberry",
  "boysenberry",
  "loganberry",
  "lingonberry",
  "huckleberry",
  "elderberry",
  "bilberry",
  "cloudberry",
  "salmonberry",
  "goji berry",
  "aubergine",
  "courgette",
  "leek",
  "marrow",
  "sweetcorn",
  "artichoke",
  "asparagus",
  "beetroot",
  "brussels sprouts",
  "cabbage",
  "carrot",
  "cauliflower",
  "celery",
  "chilli pepper",
  "corn",
  "cucumber",
  "garlic",
  "ginger",
  "kale",
  "leek",
  "lettuce",
  "mushroom",
  "onion",
  "parsnip",
  "pepper",
  "potato",
  "pumpkin",
  "radish",
  "shallot",
  "spinach",
  "squash",
  "tomato",
  "turnip",
  "swede",
  "watercress",
  "water chestnut",
  "water spinach",
  "yam",
  "zucchini",
  "acorn squash",
  "butternut squash",
  "spaghetti squash",
  "hubbard squash",
  "calabaza",
  "gem squash",
  "crookneck squash",
  "pattypan squash",
  "kabocha squash",
  "chayote",
  "tat soi",
  "broccoli rabe",
  "endive",
  "fennel",
  "okra",
  "rampion",
  "artichoke",
  "arugula",
  "aubergine",
  "beetroot",
  "bell pepper",
  "bitter melon",
  "black radish",
  "bok choy",
  "broad beans",
  "broccoflower",
  "broccoli",
  "brussels sprouts",
  "cabbage",
  "calabrese",
  "carrot",
  "cauliflower",
  "celeriac",
  "celery",
  "chard",
  "chayote",
  "chickpeas",
  "chili pepper",
  "chinese cabbage",
  "chinese spinach",
  "chinese yardlong bean",
  "cilantro",
  "collard greens",
  "coriander",
  "corn salad",
  "courgette",
  "cress",
  "cucumber",
  "daikon",
  "dandelion",
  "eggplant",
  "endive",
  "fennel",
  "fiddlehead greens",
  "frisee",
  "garlic",
  "gem squash",
  "ginger",
  "green bean",
  "green pepper",
  "herb",
  "horseradish",
  "iceberg lettuce",
  "jerusalem artichoke",
  "jicama",
  "kale",
  "kohlrabi",
  "leek",
  "legume",
  "lettuce",
  "lima bean",
  "mangetout",
  "marrow",
  "mushroom",
  "mustard greens",
  "mustard plant",
  "nappa cabbage",
  "okra",
  "onion",
  "parsley",
  "parsnip",
  "pattypan squash",
  "pea",
  "pepper",
  "pimiento",
  "potato",
  "pumpkin",
  "radicchio",
  "radish",
  "rhubarb",
  "rocket",
  "rutabaga",
  "scallion",
  "shallot",
  "silverbeet",
  "snap pea",
  "snow peas",
  "sorrel",
  "soybean",
  "spinach",
  "squash",
  "string bean",
  "sweet potato",
  "swiss chard",
  "tabasco pepper",
  "tat soi",
  "tomatillo",
  "tomato",
  "tubers",
  "turnip",
  "vegetable",
  "wasabi",
  "water chestnut",
  "watercress",
  "water spinach",
  "white radish",
  "yam",
  "yellow squash",
  "zucchini",
  "bean sprout",
  "broccolini",
  "cape gooseberry",
  "chicory",
  "chinese broccoli",
  "cucumber",
  "endive",
  "jerusalem artichoke",
  "jicama",
  "malabar spinach",
  "mangetout",
  "okra",
  "radicchio",
  "rhubarb",
  "salsify",
  "skirret",
  "tat soi",
  "tubers",
  "wasabi",
  "water chestnut",
  "watercress",
  "zucchini",
  "anise",
  "basil",
  "caraway",
  "cardamom",
  "chervil",
  "chive",
  "cilantro",
  "coriander",
  "cumin",
  "curry leaf",
  "dill",
  "fenugreek",
  "kaffir lime",
  "lavender",
  "lemongrass",
  "marjoram",
  "mint",
  "oregano",
  "parsley",
  "rosemary",
  "sage",
  "sorrel",
  "tarragon",
  "thyme",
  "watercress",
  "chili pepper",
  "garlic",
  "ginger",
  "horseradish",
  "onion",
  "shallot",
  "wasabi",
  "turmeric",
  "asparagus",
  "bamboo shoots",
  "beet",
  "bell pepper",
  "bitter melon",
  "broccoli",
  "brussels sprouts",
  "cabbage",
  "carrot",
  "cauliflower",
  "celery",
  "chayote",
  "courgette",
  "daikon",
  "endive",
  "fennel",
  "fiddlehead ferns",
  "globe artichoke",
  "green bean",
  "jicama",
  "kohlrabi",
  "leek",
  "lentil",
  "lettuce",
  "mushroom",
  "nopale",
  "okra",
  "olive",
  "parsnip",
  "pea",
  "pumpkin",
  "radicchio",
  "rhubarb",
  "rutabaga",
  "spinach",
  "squash",
  "swede",
  "sweet corn",
  "sweet potato",
  "tomato",
  "turnip",
  "water chestnut",
  "watercress",
  "water spinach",
  "yam",
  "zucchini",
  "acorn squash",
  "butternut squash",
  "spaghetti squash",
  "hubbard squash",
  "calabaza",
  "gem squash",
  "crookneck squash",
  "pattypan squash",
  "kabocha squash",
  "chayote",
  "tat soi",
  "broccoli rabe",
  "endive",
  "fennel",
  "okra",
  "rampion",
  "artichoke",
  "arugula",
  "aubergine",
  "beetroot",
  "bell pepper",
  "bitter melon",
  "black radish",
  "bok choy",
  "broad beans",
  "broccoflower",
  "broccoli",
  "brussels sprouts",
  "cabbage",
  "calabrese",
  "carrot",
  "cauliflower",
  "celeriac",
  "celery",
  "chard",
  "chayote",
  "chickpeas",
  "chili pepper",
  "chinese cabbage",
  "chinese spinach",
  "chinese yardlong bean",
  "cilantro",
  "collard greens",
  "coriander",
  "corn salad",
  "courgette",
  "cress",
  "cucumber",
  "daikon",
  "dandelion",
  "eggplant",
  "endive",
  "fennel",
  "fiddlehead greens",
  "frisee",
  "garlic",
  "gem squash",
  "ginger",
  "green bean",
  "green pepper",
  "herb",
  "horseradish",
  "iceberg lettuce",
  "jerusalem artichoke",
  "jicama",
  "kale",
  "kohlrabi",
  "leek",
  "legume",
  "lettuce",
  "lima bean",
  "mangetout",
  "marrow",
  "mushroom",
  "mustard greens",
  "mustard plant",
  "nappa cabbage",
  "okra",
  "onion",
  "parsley",
  "parsnip",
  "pattypan squash",
  "pea",
  "pepper",
  "pimiento",
  "potato",
  "pumpkin",
  "radicchio",
  "radish",
  "rhubarb",
  "rocket",
  "rutabaga",
  "scallion",
  "shallot",
  "silverbeet",
  "snap pea",
  "snow peas",
  "sorrel",
  "soybean",
  "spinach",
  "squash",
  "string bean",
  "sweet potato",
  "swiss chard",
  "tabasco pepper",
  "tat soi",
  "tomatillo",
  "tomato",
  "tubers",
  "turnip",
  "vegetable",
  "wasabi",
  "water chestnut",
  "watercress",
  "water spinach",
  "white radish",
  "yam",
  "yellow squash",
  "zucchini",
  "bean sprout",
  "broccolini",
  "cape gooseberry",
  "chicory",
  "chinese broccoli",
  "cucumber",
  "endive",
  "jerusalem artichoke",
  "jicama",
  "malabar spinach",
  "mangetout",
  "okra",
  "radicchio",
  "rhubarb",
  "salsify",
  "skirret",
  "tat soi",
  "tubers",
  "wasabi",
  "water chestnut",
  "watercress",
  "zucchini",
  "anise",
  "basil",
  "caraway",
  "cardamom",
  "chervil",
  "chive",
  "cilantro",
  "coriander",
  "cumin",
  "curry leaf",
  "dill",
  "fenugreek",
  "kaffir lime",
  "lavender",
  "lemongrass",
  "marjoram",
  "mint",
  "oregano",
  "parsley",
  "rosemary",
  "sage",
  "sorrel",
  "tarragon",
  "thyme",
  "watercress",
  "chili pepper",
  "garlic",
  "ginger",
  "horseradish",
  "onion",
  "shallot",
  "wasabi",
  "turmeric",
  "asparagus",
  "bamboo shoots",
  "beet",
  "bell pepper",
  "bitter melon",
  "broccoli",
  "brussels sprouts",
  "cabbage",
  "carrot",
  "cauliflower",
  "celery",
  "chayote",
  "courgette",
  "daikon",
  "endive",
  "fennel",
  "fiddlehead ferns",
  "globe artichoke",
  "green bean",
  "jicama",
  "kohlrabi",
  "leek",
  "lentil",
  "lettuce",
  "mushroom",
  "nopale",
  "okra",
  "olive",
  "parsnip",
  "pea",
  "pumpkin",
  "radicchio",
  "rhubarb",
  "rutabaga",
  "spinach",
  "squash",
  "swede",
  "sweet corn",
  "sweet potato",
  "tomato",
  "turnip",
  "water chestnut",
  "watercress",
  "water spinach",
  "yam",
  "zucchini",
  "acorn squash",
  "butternut squash",
  "spaghetti squash",
  "hubbard squash",
  "calabaza",
  "gem squash",
  "crookneck squash",
  "pattypan squash",
  "kabocha squash",
  "chayote",
  "tat soi",
  "broccoli rabe",
  "endive",
  "fennel",
  "okra",
  "rampion",
  "artichoke",
  "arugula",
  "aubergine",
  "beetroot",
  "bell pepper",
  "bitter melon",
  "black radish",
  "bok choy",
  "broad beans",
  "broccoflower",
  "broccoli",
  "brussels sprouts",
  "cabbage",
  "calabrese",
  "carrot",
  "cauliflower",
  "celeriac",
  "celery",
  "chard",
  "chayote",
  "chickpeas",
  "chili pepper",
  "chinese cabbage",
  "chinese spinach",
  "chinese yardlong bean",
  "cilantro",
  "collard greens",
  "coriander",
  "corn salad",
  "courgette",
  "cress",
  "cucumber",
  "daikon",
  "dandelion",
  "eggplant",
  "endive",
  "fennel",
  "fiddlehead greens",
  "frisee",
  "garlic",
  "gem squash",
  "ginger",
  "green bean",
  "green pepper",
  "herb",
  "horseradish",
  "iceberg lettuce",
  "jerusalem artichoke",
  "jicama",
  "kale",
  "kohlrabi",
  "leek",
  "legume",
  "lettuce",
  "lima bean",
  "mangetout",
  "marrow",
  "mushroom",
  "mustard greens",
  "mustard plant",
  "nappa cabbage",
  "okra",
  "onion",
  "parsley",
  "parsnip",
  "pattypan squash",
  "pea",
  "pepper",
  "pimiento",
  "potato",
  "pumpkin",
  "radicchio",
  "radish",
  "rhubarb",
  "rocket",
  "rutabaga",
  "scallion",
  "shallot",
  "silverbeet",
  "snap pea",
  "snow peas",
  "sorrel",
  "soybean",
  "spinach",
  "squash",
  "string bean",
  "sweet potato",
  "swiss chard",
  "tabasco pepper",
  "tat soi",
  "tomatillo",
  "tomato",
  "tubers",
  "turnip",
  "vegetable",
  "wasabi",
  "water chestnut",
  "watercress",
  "water spinach",
  "white radish",
  "yam",
  "yellow squash",
  "zucchini",
  "bean sprout",
  "broccolini",
  "cape gooseberry",
  "chicory",
  "chinese broccoli",
  "cucumber",
  "endive",
  "jerusalem artichoke",
  "jicama",
  "malabar spinach",
  "mangetout",
  "okra",
  "radicchio",
  "rhubarb",
  "salsify",
  "skirret",
  "tat soi",
  "tubers",
  "wasabi",
  "water chestnut",
  "watercress",
  "zucchini",
  "anise",
  "basil",
  "caraway",
  "cardamom",
  "chervil",
  "chive",
  "cilantro",
  "coriander",
  "cumin",
  "curry leaf",
  "dill",
  "fenugreek",
  "kaffir lime",
  "lavender",
  "lemongrass",
  "marjoram",
  "mint",
  "oregano",
  "parsley",
  "rosemary",
  "sage",
  "sorrel",
  "tarragon",
  "thyme",
  "watercress",
  "chili pepper",
  "garlic",
  "ginger",
  "horseradish",
  "onion",
  "shallot",
  "wasabi",
  "turmeric",
  "asparagus",
  "bamboo shoots",
  "beet",
  "bell pepper",
  "bitter melon",
  "broccoli",
  "brussels sprouts",
  "cabbage",
  "carrot",
  "cauliflower",
  "celery",
  "chayote",
  "courgette",
  "daikon",
  "endive",
  "fennel",
  "fiddlehead ferns",
  "globe artichoke",
  "green bean",
  "jicama",
  "kohlrabi",
  "leek",
  "lentil",
  "lettuce",
  "mushroom",
  "nopale",
  "okra",
  "olive",
  "parsnip",
  "pea",
  "pumpkin",
  "radicchio",
  "rhubarb",
  "rutabaga",
  "spinach",
  "squash",
  "swede",
  "sweet corn",
  "sweet potato",
  "tomato",
  "turnip",
  "water chestnut",
  "watercress",
  "water spinach",
  "yam",
  "zucchini",
  "acorn squash",
  "butternut squash",
  "spaghetti squash",
  "hubbard squash",
  "calabaza",
  "gem squash",
  "crookneck squash",
  "pattypan squash",
  "kabocha squash",
  "chayote",
  "tat soi",
  "broccoli rabe",
  "endive",
  "fennel",
  "okra",
  "rampion",
  "artichoke",
  "arugula",
  "aubergine",
  "beetroot",
  "bell pepper",
  "bitter melon",
  "black radish",
  "bok choy",
  "broad beans",
  "broccoflower",
  "broccoli",
  "brussels sprouts",
  "cabbage",
  "calabrese",
  "carrot",
  "cauliflower",
  "celeriac",
  "celery",
  "chard",
  "chayote",
  "chickpeas",
  "chili pepper",
  "chinese cabbage",
  "chinese spinach",
  "chinese yardlong bean",
  "cilantro",
  "collard greens",
  "coriander",
  "corn salad",
  "courgette",
  "cress",
  "cucumber",
  "daikon",
  "dandelion",
  "eggplant",
  "endive",
  "fennel",
  "fiddlehead greens",
  "frisee",
  "garlic",
  "gem squash",
  "ginger",
  "green bean",
  "green pepper",
  "herb",
  "horseradish",
  "iceberg lettuce",
  "jerusalem artichoke",
  "jicama",
  "kale",
  "kohlrabi",
  "leek",
  "legume",
  "lettuce",
  "lima bean",
  "mangetout",
  "marrow",
  "mushroom",
  "mustard greens",
  "mustard plant",
  "nappa cabbage",
  "okra",
  "onion",
  "parsley",
  "parsnip",
  "pattypan squash",
  "pea",
  "pepper",
  "pimiento",
  "potato",
  "pumpkin",
  "radicchio",
  "radish",
  "rhubarb",
  "rocket",
  "rutabaga",
  "scallion",
  "shallot",
  "silverbeet",
  "snap pea",
  "snow peas",
  "sorrel",
  "soybean",
  "spinach",
  "squash",
  "string bean",
  "sweet potato",
  "swiss chard",
  "tabasco pepper",
  "tat soi",
  "tomatillo",
  "tomato",
  "tubers",
  "turnip",
  "vegetable",
  "wasabi",
  "water chestnut",
  "watercress",
  "water spinach",
  "white radish",
  "yam",
  "yellow squash",
  "zucchini",
  "bean sprout",
  "broccolini",
  "cape gooseberry",
  "chicory",
  "chinese broccoli",
  "cucumber",
  "endive",
  "jerusalem artichoke",
  "jicama",
  "malabar spinach",
  "mangetout",
  "okra",
  "radicchio",
  "rhubarb",
  "salsify",
  "skirret",
  "tat soi",
  "tubers",
  "wasabi",
  "water chestnut",
  "watercress",
  "zucchini",
  "anise",
  "basil",
  "caraway",
  "cardamom",
  "chervil",
  "chive",
  "cilantro",
  "coriander",
  "cumin",
  "curry leaf",
  "dill",
  "fenugreek",
  "kaffir lime",
  "lavender",
  "lemongrass",
  "marjoram",
  "mint",
  "oregano",
  "parsley",
  "rosemary",
  "sage",
  "sorrel",
  "tarragon",
  "thyme",
  "watercress",
  "chili pepper",
  "garlic",
  "ginger",
  "horseradish",
  "onion",
  "shallot",
  "wasabi",
  "turmeric",
  "asparagus",
  "bamboo shoots",
  "beet",
  "bell pepper",
  "bitter melon",
  "broccoli",
  "brussels sprouts",
  "cabbage",
  "carrot",
  "cauliflower",
  "celery",
  "chayote",
  "courgette",
  "daikon",
  "endive",
  "fennel",
  "fiddlehead ferns",
  "globe artichoke",
  "green bean",
  "jicama",
  "kohlrabi",
  "leek",
  "lentil",
  "lettuce",
  "mushroom",
  "nopale",
  "okra",
  "olive",
  "parsnip",
  "pea",
  "pumpkin",
  "radicchio",
  "rhubarb",
  "rutabaga",
  "spinach",
  "squash",
  "swede",
  "sweet corn",
  "sweet potato",
  "tomato",
  "turnip",
  "water chestnut",
  "watercress",
  "water spinach",
  "yam",
  "zucchini",
  "acorn squash",
  "butternut squash",
  "spaghetti squash",
  "hubbard squash",
  "calabaza",
  "gem squash",
  "crookneck squash",
  "pattypan squash",
  "kabocha squash",
  "chayote",
  "tat soi",
  "broccoli rabe",
  "endive",
  "fennel",
  "okra",
  "rampion",
  "artichoke",
  "arugula",
  "aubergine",
  "beetroot",
  "bell pepper",
  "bitter melon",
  "black radish",
  "bok choy",
  "broad beans",
  "broccoflower",
  "broccoli",
  "brussels sprouts",
  "cabbage",
  "calabrese",
  "carrot",
  "cauliflower",
  "celeriac",
  "celery",
  "chard",
  "chayote",
  "chickpeas",
  "chili pepper",
  "chinese cabbage",
  "chinese spinach",
  "chinese yardlong bean",
  "cilantro",
  "collard greens",
  "coriander",
  "corn salad",
  "courgette",
  "cress",
  "cucumber",
  "daikon",
  "dandelion",
  "eggplant",
  "endive",
  "fennel",
  "fiddlehead greens",
  "frisee",
  "garlic",
  "gem squash",
  "ginger",
  "green bean",
  "green pepper",
  "herb",
  "horseradish",
  "iceberg lettuce",
  "jerusalem artichoke",
  "jicama",
  "kale",
  "kohlrabi",
  "leek",
  "legume",
  "lettuce",
  "lima bean",
  "mangetout",
  "marrow",
  "mushroom",
  "mustard greens",
  "mustard plant",
  "nappa cabbage",
  "okra",
  "onion",
  "parsley",
  "parsnip",
  "pattypan squash",
  "pea",
  "pepper",
  "pimiento",
  "potato",
  "pumpkin",
  "radicchio",
  "radish",
  "rhubarb",
  "rocket",
  "rutabaga",
  "scallion",
  "shallot",
  "silverbeet",
  "snap pea",
  "snow peas",
  "sorrel",
  "soybean",
  "spinach",
  "squash",
  "string bean",
  "sweet potato",
  "swiss chard",
  "tabasco pepper",
  "tat soi",
  "tomatillo",
  "tomato",
  "tubers",
  "turnip",
  "vegetable",
  "wasabi",
  "water chestnut",
  "watercress",
  "water spinach",
  "white radish",
  "yam",
  "yellow squash",
  "zucchini",
  "bean sprout",
  "broccolini",
  "cape gooseberry",
  "chicory",
  "chinese broccoli",
  "cucumber",
  "endive",
  "jerusalem artichoke",
  "jicama",
  "malabar spinach",
  "mangetout",
  "okra",
  "radicchio",
  "rhubarb",
  "salsify",
  "skirret",
  "tat soi",
  "tubers",
  "wasabi",
  "water chestnut",
  "watercress",
  "zucchini",
  "anise",
  "basil",
  "caraway",
  "cardamom",
  "chervil",
  "chive",
  "cilantro",
  "coriander",
  "cumin",
  "curry leaf",
  "dill",
  "fenugreek",
  "kaffir lime",
  "lavender",
  "lemongrass",
  "marjoram",
  "mint",
  "oregano",
  "parsley",
  "rosemary",
  "sage",
  "sorrel",
  "tarragon",
  "thyme",
  "watercress",
  "chili pepper",
  "garlic",
  "ginger",
  "horseradish",
  "onion",
  "shallot",
  "wasabi",
  "turmeric",
  "asparagus",
  "bamboo shoots",
  "beet",
  "bell pepper",
  "bitter melon",
  "broccoli",
  "brussels sprouts",
  "cabbage",
  "carrot",
  "cauliflower",
  "celery",
  "chayote",
  "courgette",
  "daikon",
  "endive",
  "fennel",
  "fiddlehead ferns",
  "globe artichoke",
  "green bean",
  "jicama",
  "kohlrabi",
  "leek",
  "lentil",
  "lettuce",
  "mushroom",
  "nopale",
  "okra",
  "olive",
  "parsnip",
  "pea",
  "pumpkin",
  "radicchio",
  "rhubarb",
  "rutabaga",
  "spinach",
  "squash",
  "swede",
  "sweet corn",
  "sweet potato",
  "tomato",
  "turnip",
  "water chestnut",
  "watercress",
  "water spinach",
  "yam",
  "zucchini",
  "acorn squash",
  "butternut squash",
  "spaghetti squash",
  "hubbard squash",
  "calabaza",
  "gem squash",
  "crookneck squash",
  "pattypan squash",
  "kabocha squash",
  "chayote",
  "tat soi",
  "broccoli rabe",
  "endive",
  "fennel",
  "okra",
  "rampion",
  "artichoke",
  "arugula",
  "aubergine",
  "beetroot",
  "bell pepper",
  "bitter melon",
  "black radish",
  "bok choy",
  "broad beans",
  "broccoflower",
  "broccoli",
  "brussels sprouts",
  "cabbage",
  "calabrese",
  "carrot",
];

let palabraAleatoria, time, score;

function randomWords() {
  const randomIndex = Math.floor(Math.random() * words.length);
  return words[randomIndex];
}

function addToDOM() {
  palabraAleatoria = randomWords();
  document.getElementById("randomWord").textContent = palabraAleatoria;
}

function actualizarTiempo() {
  time = 10;
  const timeSpan = document.getElementById("timeSpan");
  const countdown = setInterval(() => {
    time--;
    timeSpan.textContent = time + "s";
    if (time === 0) {
      clearInterval(countdown);
      gameOver();
    }
  }, 1000);
}

function updateScore() {
  score = score || 0; // Initialize score to 0 if it's undefined
  score++;
  document.getElementById("score").textContent = score;
}

function gameOver() {
  const endGameContainer = document.getElementById("end-game-container");
  const finalScore = score || 0; // Use 0 if score is undefined
  endGameContainer.innerHTML = `
      <h2>Se acabó el tiempo!</h2>
      <p>Puntaje final: ${finalScore}</p>
      <button onclick="location.reload()">Jugar de nuevo</button>
    `;
}

document.getElementById("text").addEventListener("input", (e) => {
  const palabraIngresada = e.target.value.trim();
  if (palabraIngresada === palabraAleatoria) {
    time += 3;
    e.target.value = "";
    addToDOM();
    updateScore();
  }
});

addToDOM();
actualizarTiempo();
